MoneyTreeWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    # path('about/', views.about, name='about'),
    path('detail/<name>', views.detail, name='detail'),
    # path('service/', views.service, name='service'),
    # path('appointment/', views.appointment, name='appointment'),
]

home/models.py
from email import message
from email.policy import default
from django.db import models
from django.forms import BooleanField
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(verbose_name="email", max_length=60)
    contact_no = PhoneNumberField(null=False, blank=False)
    subject = models.CharField(max_length=500)
    message = models.TextField()
    is_replied = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.created_at = timezone.now()
        # self.updated_at = timezone.now()
        return super(Contact, self).save(*args, **kwargs)

home/views.py
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.core.mail import send_mail
from django.urls import reverse

from home.models import Contact
from datetime import datetime


def home(request):
    return render(request, 'home.html', {})


def contact(request):
    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message_sub = request.POST['message-sub']
        message = request.POST['message']
        contact_no = request.POST['phno']

        con_db = Contact(
            name = message_name,
            email = message_email,
            subject = message_sub,
            message = message,
            contact_no = contact_no
        )
        con_db.save()

        msg_frm = f"from: {message_email}\n\n" + message
        # send mail
        print(msg_frm)
        send_mail(
            message_sub,
            msg_frm,
            message_email,
            [settings.EMAIL_HOST_USER],
        )

        return render(request, 'contact.html', {'message_name': message_name})

    else: 
        return render(request, 'contact.html', {})
    

def detail(request, name):
    return render(request, 'detail.html', {'name':name})

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>CONSULT - Consultancy Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'home/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'home/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">
</head>

<style>
.image-container {
  max-width: 200px;
  position: relative;
  overflow: hidden;
}

.image-container img {
  display: block;
  width: 100%;
  height: auto;
  object-fit: cover;
}
</style>

<div>
    <!-- Topbar Start -->
    <div class="container-fluid bg-secondary ps-5 pe-0 d-none d-lg-block">
        <div class="row gx-0">
            <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                <!-- <div class="d-inline-flex align-items-center">
                    <a class="text-body py-2 pe-3 border-end" href=""><small>FAQs</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Support</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Privacy</small></a>
                    <a class="text-body py-2 px-3 border-end" href=""><small>Policy</small></a>
                    <a class="text-body py-2 ps-3" href=""><small>Career</small></a>
                </div> -->
            </div>
            <div class="col-md-6 text-center text-lg-end">
                <div class="position-relative d-inline-flex align-items-center bg-primary text-white top-shape px-5">
                    <div class="me-3 pe-3 border-end py-2">
                        <p class="m-0"><i class="fa fa-envelope-open me-2"></i>moneytree0307@gmail.com</p>
                    </div>
                    <div class="py-2">
                        <p class="m-0"><i class="fa fa-phone-alt me-2"></i>+91 9944316900</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow-sm px-5 py-3 py-lg-0">
        <a href="{% url 'home:home' %}" class="navbar-brand p-0">
            <!-- <h1 class="m-0 text-uppercase text-primary"><i class="far fa-smile text-primary me-2"></i>MoneyTree</h1> -->
            <div class="image-container">
                <img src="{% static 'home/img/logo.jpeg' %}" alt="Image">
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0 me-n3">
                <a href="{% url 'home:home' %}" class="nav-item nav-link active">Home</a>
                <a href="about.html" class="nav-item nav-link">About</a>
                <a href="{% url 'home:home' %}#Services" class="nav-item nav-link">Service</a>
                <!-- <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                    <div class="dropdown-menu m-0">
                        <a href="blog.html" class="dropdown-item">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                        <a href="feature.html" class="dropdown-item">Features</a>
                        <a href="quote.html" class="dropdown-item">Quote Form</a>
                        <a href="team.html" class="dropdown-item">The Team</a>
                        <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                    </div>
                </div> -->
                <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact</a>
            </div>
        </div>
    </nav>
    <!-- Navbar End -->

    {% block content %}
    
      
    {% endblock content %}
    

    <!-- Footer Start -->
    <!-- <div class="container-fluid bg-primary text-secondary p-5">
        <div class="row g-5">
            <div class="col-12 text-center">
                <h1 class="display-5 mb-4">Stay Update!!!</h1>
                <form class="mx-auto" style="max-width: 600px;">
                    <div class="input-group">
                        <input type="text" class="form-control border-white p-3" placeholder="Your Email">
                        <button class="btn btn-dark px-4">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div> -->
    <div class="container-fluid bg-dark text-secondary p-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-secondary mb-2" href="{% url 'home:home' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                    <a class="text-secondary mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                    <a class="text-secondary mb-2" href="{% url 'home:home' %}#Services"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                    <a class="text-secondary" href="{% url 'home:contact' %}"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                </div>
            </div>
            
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>Chennai Office: <br>23A, Vivek Nagar, Chitlapakkam,<br> Chennai - 600064</p><br>
                <p class="mb-2"><i class="bi bi-geo-alt text-primary me-2"></i>Pondicherry Office: <br>1st Floor, 428, Cuddalore Road, <br>opp. TATA Motors, Murungapakkam, Puducherry - 605004</p><br>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Follow Us</h3>
                <div class="d-flex">
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                    <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                    <!-- <a class="btn btn-lg btn-primary btn-lg-square rounded-circle" href="#"><i class="fab fa-instagram fw-normal"></i></a> -->
                </div>
                <br>
                <p class="mb-2"><i class="bi bi-envelope-open text-primary me-2"></i>moneytree0307@gmail.com</p>
                <p class="mb-0"><i class="bi bi-telephone text-primary me-2"></i>+91 9944316900</p>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-secondary text-center border-top py-4 px-5" style="border-color: rgba(256, 256, 256, .1) !important;">
        <p class="m-0">&copy; <a class="text-secondary border-bottom" href="#">MoneyTree</a>. All Rights Reserved. Designed by <a class="text-secondary border-bottom" href="https://htmlcodex.com">HTML Codex</a></p>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'home/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'home/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'home/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'home/js/main.js' %}"></script>
</body>

</html>

home/templates/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Page Header Start -->
    <div class="container-fluid bg-dark p-5">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="display-4 text-white">Contact Us</h1>
                <a href="">Home</a>
                <i class="far fa-square text-primary px-2"></i>
                <a href="">Contact</a>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-fluid bg-secondary px-0">
        <div class="row g-0">
            <div class="col-lg-6 py-6 px-5">
                {% if message_name %}
                    <centre>
                        <h2>Hey {{ message_name }}!</h2>
                        <p>Your email has been received and will respond you shortly...</p>
                    </centre>
                {% else %}
                
                <h1 class="display-5 mb-4">Contact For Any Queries</h1>
                <form action="{% url 'home:contact' %}" method="post">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-6">
                            <div class="form-floating">
                                <input type="text" name="phno" class="form-control" id="form-floating-1" placeholder="Contact No">
                                <label for="form-floating-1">Contact No</label>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-floating">
                                <input type="email" name="message-email" class="form-control" id="form-floating-2" placeholder="name@example.com">
                                <label for="form-floating-2">Email address</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input type="text" name="message-name" class="form-control" id="form-floating-3" placeholder="Full Name">
                                <label for="form-floating-3">Full Name</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <input type="text" name="message-sub" class="form-control" id="form-floating-3" placeholder="Subject">
                                <label for="form-floating-3">Subject</label>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-floating">
                                <textarea name="message" class="form-control" placeholder="Message" id="form-floating-4" style="height: 150px"></textarea>
                                <label for="form-floating-4">Message</label>
                              </div>
                        </div>
                        <div class="col-12">
                            <button class="btn btn-primary w-100 py-3" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
            <!-- <div class="col-lg-6 py-3 px-5" style="min-height: 400px;">
                <div class="h-50" style="border:0; border: 2px solid black;">
                    <br>
                    <h4>Pondicherry</h4>
                    <iframe class=" position-relative w-100 h-70" 
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12853.628936790967!2d79.80090179211554!3d11.914214704364515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a536114cdf4d941%3A0x2e3a67aeda8502fc!2sMoneyTree%20Consultant!5e0!3m2!1sen!2sin!4v1688575327566!5m2!1sen!2sin"
                        frameborder="0" style="border:0; border: 2px solid black;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe> 
                        <br><br>
                </div>
                <div class=" h-50" style="border:0; border: 2px solid black;">
                    <br>
                    <h4>Pondicherry</h4>
                    <iframe class="w-100 h-70"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12853.628936790967!2d79.80090179211554!3d11.914214704364515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a536114cdf4d941%3A0x2e3a67aeda8502fc!2sMoneyTree%20Consultant!5e0!3m2!1sen!2sin!4v1688575327566!5m2!1sen!2sin"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe> 
                        <br><br>
                </div>

            </div> -->
            <div class="col-lg-6 py-3 px-5" style="min-height: 400px; display: flex; flex-direction: column; gap: 20px;">
                <div class="flex-grow-1" style="flex-grow: 0.6; padding: 10px;">
                    <h4>Pondicherry Office</h4>
                    <iframe class="w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12853.628936790967!2d79.80090179211554!3d11.914214704364515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a536114cdf4d941%3A0x2e3a67aeda8502fc!2sMoneyTree%20Consultant!5e0!3m2!1sen!2sin!4v1688575327566!5m2!1sen!2sin"
                        frameborder="0" style="border: 0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
                <br>
                <div class="flex-grow-1" style="flex-grow: 0.4; padding: 10px;">
                    <h4>Chennai Office</h4>
                    <iframe class="w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d394.9483529657023!2d80.14487926135195!3d12.93625717509515!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a525efe66a0da19%3A0xb1cf2fc945925f9b!2s23A%2C%20Vivek%20Nagar%2C%20MC%20Nagar%2C%20Chitlapakkam%2C%20Chennai%2C%20Tamil%20Nadu%20600064!5e0!3m2!1sen!2sin!4v1699908565542!5m2!1sen!2sin" 
                        frameborder="0" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
                
            </div>
            
        </div>
        <br><br>
        {% endif %}
    </div>
    <!-- Contact End -->

 {% endblock content %}